### ISSUE TITLE
Automatic release to rubygems not working

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash-ruby#18]
For 0.1.2 we manually pushed the gem to rubygems.org. The deploy failed with
```
/home/travis/.rvm/gems/ruby-2.4.5/gems/gems-1.2.0/lib/gems/request.rb:77:in `body_from_response': Access Denied. Please sign up for an account at https://rubygems.org (Gems::GemError)
275	from /home/travis/.rvm/gems/ruby-2.4.5/gems/gems-1.2.0/lib/gems/request.rb:57:in `request'
276	from /home/travis/.rvm/gems/ruby-2.4.5/gems/gems-1.2.0/lib/gems/request.rb:17:in `post'
277	from /home/travis/.rvm/gems/ruby-2.4.5/gems/gems-1.2.0/lib/gems/client.rb:67:in `push'
278	from /home/travis/.rvm/gems/ruby-2.4.5/gems/gems-1.2.0/lib/gems.rb:17:in `method_missing'
279	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-rubygems-1.10.13/lib/dpl/provider/rubygems.rb:45:in `block in push_app'
280	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-rubygems-1.10.13/lib/dpl/provider/rubygems.rb:41:in `glob'
281	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-rubygems-1.10.13/lib/dpl/provider/rubygems.rb:41:in `push_app'
282	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/provider.rb:199:in `block in deploy'
283	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/cli.rb:41:in `fold'
284	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/provider.rb:199:in `deploy'
285	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/cli.rb:32:in `run'
286	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/lib/dpl/cli.rb:7:in `run'
287	from /home/travis/.rvm/gems/ruby-2.4.5/gems/dpl-1.10.13/bin/dpl:5:in `<top (required)>'
288	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `load'
289	from /home/travis/.rvm/gems/ruby-2.4.5/bin/dpl:23:in `<main>'
290failed to deploy
```

My best guess is that we need to re-encrypt the deploy secret. Alternative is there's a bug in one of the gems in the stacktrace above and we need to update the version.

**Comment by MikaelSmith** [comment]
Still not working. Deploy using the api key locally works
```
dpl --provider=rubygems --api-key=<key> --app=wash
```
I have to assume I encrypted it incorrectly somehow, although I followed the instructions at https://docs.travis-ci.com/user/deployment/rubygems/.
