### ISSUE TITLE
Example fails 'wash validate'

### ISSUE THREAD

**Issue by MikaelSmith** [puppetlabs/wash-ruby#2]
I installed the gem, then ran `wash validate examples/mock_docker.rb`:
```
Error loading plugin: script returned a non-zero exit code of 1
COMMAND: (PID 55525) (PGID 55525) examples/mock_docker.rb init null
STDERR:
examples/mock_docker.rb:22:in `init': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/michaelsmith/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/wash-0.0.0/lib/wash.rb:62:in `run'
	from examples/mock_docker.rb:184:in `<main>'
See https://puppetlabs.github.io/wash/docs/external_plugins/#init for response format
```

**Comment by MikaelSmith** [comment]
With the latest code on wash#master, this is resolved.
